#!/bin/sh

# Warning flags.
WARNFLAGS="-Werror -Werror-pointer-arith -Wall -Wsystem-headers \
-Wold-style-definition -Wreturn-type -Wwrite-strings -Wswitch \
-Wchar-subscripts -Wnested-externs -Wshadow -Wmissing-prototypes \
-Wstrict-prototypes -Wmissing-variable-declarations -Wthread-safety \
-Wsign-compare -Wundef -Wno-comment"

# Installation directory.
: ${PREFIX:=/usr/local}

# Host toolchain parameters.
: ${CC:=cc}
: ${CFLAGS:=-O2 -I${PREFIX}/include ${WARNFLAGS}}
: ${LDFLAGS:=-L${PREFIX}/lib}

# CloudABI toolchain parameters.
: ${CLOUDABI_CC:=x86_64-unknown-cloudabi-cc}
: ${CLOUDABI_CFLAGS:=-O2 ${WARNFLAGS}}

set -e

rm -Rf _obj
mkdir _obj

if type clang-format > /dev/null; then
  find src -name '*.[ch]' | while read srcfile; do
    clang-format -style='{
  BasedOnStyle: Google,
  AllowShortIfStatementsOnASingleLine: false,
  AllowShortLoopsOnASingleLine: false,
  AllowShortFunctionsOnASingleLine: None,
  DerivePointerBinding: false,
  PointerAlignment: Right,
}' "${srcfile}" > _obj/clang-format
    if ! cmp -s _obj/clang-format "${srcfile}"; then
      echo "=> Style fixing ${srcfile}"
      mv _obj/clang-format "${srcfile}"
    fi
  done
fi

set -x

${CLOUDABI_CC} ${CLOUDABI_CFLAGS} ${CLOUDABI_LDFLAGS} \
    -o _obj/cloudabi-reexec src/cloudabi-reexec/*.c
${CC} ${CFLAGS} ${LDFLAGS} "-DPREFIX=\"${PREFIX}\"" -lyaml \
    -o _obj/cloudabi-run src/cloudabi-run/*.c
gzip -9nc src/cloudabi-run/cloudabi-run.1 > _obj/cloudabi-run.1.gz
